# 遵循 v1 版本的 Kubernetes API
apiVersion: v1
# 资源类型为 PersistentVolumeClaim
kind: PersistentVolumeClaim
metadata:
  # PVC 的名称
  name: mongodb-pvc
spec:
  # 资源列表
  resources:
    # 申请列表
    requests:
      # 申请 100MB 的空间
      storage: 100Mi
  # 访问模式列表
  accessModes:
    # 允许单个客户端挂载为读写模式
    - ReadWriteOnce
  # 使用的 StorageClass 资源的名称为 fast
  storageClassName: fast
