# 遵循 v1 版本的 Kubernetes API
apiVersion: v1
# 资源类型为 ResourceQuota
kind: ResourceQuota
metadata:
  # ResourceQuota 的名称
  name: cpu-and-mem
spec:
  hard:
    # 【注意类型， hard 字段的类型是 map[string]string】
    # 命名空间中所有 Pod 的 CPU 和内存请求量之和的最大值
    requests.cpu: 400m
    requests.memory: 200Mi
    # 命名空间中所有 Pod 的 CPU 和内存限制量之和的最大值
    limits.cpu: 600m
    limits.memory: 500Mi
    # 命名空间中所有 PVC 可声明的存储总量
    requests.storage: 500Gi
    # 命名空间 StorageClass 可声明的 SSD 存储总量
    ssd.storageclass.storage.k8s.io/requests.storage: 300Gi
    # 命名空间 StorageClass 可声明的 HDD 存储总量
    standard.storageclass.storage.k8s.io/requests.storage: 1Ti
    # 命名空间中最多创建的各类资源数量
    pods: 10
    replicationcontrollers: 5
    secrets: 10
    configmaps: 10
    persistentvolumeclaims: 4
    # 命名空间最多创建 5 个 Service ，
    # 其中最多 1 个 LoadBalancer ，最多 2 个 NodePort 类型
    services: 5
    services.loadbalancers: 1
    services.nodeports: 2
    # 命名空间 StorageClass 可声明为 SSD 的 PVC 的数量
    ssd.storageclass.storage.k8s.io/persistentvolumeclaims: 300Gi
