# 第一个资源遵循 apps/v1 版本的 Kubernetes API
apiVersion: apps/v1
# 资源类型为 StatefulSet
kind: StatefulSet
metadata:
  # StatefulSet 的名称
  name: kubia
spec:
  # StatefulSet 的控制 Service 的名字
  serviceName: kubia
  selector:
    # 需要匹配以下指定的标签
    matchLabels:
      app: kubia
  # 最大副本数为 2
  replicas: 2
  # Pod 模版
  template:
    # Pod 含有 app=kubia 标签
    metadata:
      labels:
        app: kubia
    spec:
      # Pod 含有一个名为 kubia 的容器
      containers:
        - name: kubia
          image: idealism/kubia-pet
          # 该容器的端口列表
          ports:
            # 第一个可用的端口为 8080 ，名字是 http
            - name: http
              containerPort: 8080
          # 该容器挂载列表
          volumeMounts:
            # 将名为 data 的卷挂载到容器的 /var/data
            - name: data
              mountPath: /var/data
  # 持久卷声明模版
  volumeClaimTemplates:
    - metadata:
        # 名为 data
        name: data
      spec:
        resources:
          # 申请 1MB 的空间
          requests:
            storage: 1Mi
        # 访问模式列表
        accessModes:
          # 可以被单个客户端挂载为读写模式
          - ReadWriteOnce
