# 第一个资源遵循 v1 版本的 Kubernetes API
apiVersion: v1
# 资源类型为 Service
kind: Service
metadata:
  # Service 的名称
  name: kubia
spec:
  # Stateful 的控制 Service 必须是 headless 模式
  clusterIP: None
  # 所有标签为 app=kubia 的 Pod 都属于这个 Service
  selector:
    app: kubia
  # 该服务可用的端口
  ports:
    # 第一个可用端口的名字
    - name: http
      # 可用端口为 80
      port: 80
